# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190212_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField(blank=True, max_length=11)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='ad_images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=7)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(blank=True, max_length=11)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(),
        ),
    ]
